services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fps-logs-analyzer-api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/fps_logs_analyzer
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "npx prisma migrate deploy && node dist/main.js"
    restart: unless-stopped
    networks:
      - app-network

  postgres:
    image: bitnami/postgresql:17
    container_name: fps-logs-analyzer-db
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres123
      - POSTGRESQL_DATABASE=fps_logs_analyzer
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/bitnami/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d fps_logs_analyzer']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
